<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Debug Test Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>6af94000-af2c-4547-8a78-9a4dee6380f2</testSuiteGuid>
   <testCaseLink>
      <guid>ae7b450d-12f2-4e0b-b229-4d9e97dfc1f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android 7, 8, 9, 10/Wallets workflow/0 - Start</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>cbe38f94-7896-4da0-83f9-86b96bc35e6d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android 7, 8, 9, 10/Wallets workflow/3 - Mnemonic workflow</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcd882c0-74d8-469c-80be-e441e669842f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43b7e493-c1df-4954-8d7a-187f7585c4be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4d7b6ed-0767-480f-a009-def45eebaa8d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74473a30-1ef0-4359-b079-2476b385bfa9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14e39ff6-8c59-4baf-9197-67b5f2b41d53</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
